namespace Skysim.Logger.Api.Contracts.DTOs;

public record LogFlowSummaryDto(
    string FlowId,
    string FlowType,
    string? CheckoutType,
    string Status,
    string? UserId,
    string? UserEmail,
    string? Username,
    string? PartnerId,
    string? CustomerEmail,
    string? CustomerPhone,
    string? OrderId,
    string? OrderCode,
    string? PaymentId,
    string? TransactionId,
    int TotalSteps,
    int SuccessSteps,
    int FailedSteps,
    string? LastActionType,
    string? LastMessage,
    string? LastServiceName,
    DateTime StartedAt,
    DateTime? CompletedAt,
    DateTime CreatedAt,
    DateTime UpdatedAt);
