// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skysim.Logger.Infrastructure.Data;

#nullable disable

namespace Skysim.Logger.Infrastructure.Migrations
{
    [DbContext(typeof(LoggerDbContext))]
    [Migration("20260707000000_AddTransactionIdToLogFlows")]
    partial class AddTransactionIdToLogFlows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_time");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_time");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("idx_log_actions_action_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_actions_created_at");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("idx_log_actions_event_id");

                    b.HasIndex("FlowId")
                        .HasDatabaseName("idx_log_actions_flow_id");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("idx_log_actions_service_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_log_actions_status");

                    b.ToTable("log_actions", (string)null);
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogActionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_payload");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ActionId")
                        .IsUnique()
                        .HasDatabaseName("idx_log_action_details_action_id");

                    b.ToTable("log_action_details", (string)null);
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CheckoutType")
                        .HasColumnType("text")
                        .HasColumnName("checkout_type");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<int>("FailedSteps")
                        .HasColumnType("integer")
                        .HasColumnName("failed_steps");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_id");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_type");

                    b.Property<string>("LastActionType")
                        .HasColumnType("text")
                        .HasColumnName("last_action_type");

                    b.Property<string>("LastMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_message");

                    b.Property<string>("OrderCode")
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<string>("OrderId")
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<string>("PartnerId")
                        .HasColumnType("text")
                        .HasColumnName("partner_id");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text")
                        .HasColumnName("payment_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SuccessSteps")
                        .HasColumnType("integer")
                        .HasColumnName("success_steps");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutType")
                        .HasDatabaseName("idx_log_flows_checkout_type");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("idx_log_flows_completed_at");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_log_flows_created_at");

                    b.HasIndex("CustomerEmail")
                        .HasDatabaseName("idx_log_flows_customer_email");

                    b.HasIndex("CustomerPhone")
                        .HasDatabaseName("idx_log_flows_customer_phone");

                    b.HasIndex("FlowId")
                        .IsUnique()
                        .HasDatabaseName("idx_log_flows_flow_id");

                    b.HasIndex("FlowType")
                        .HasDatabaseName("idx_log_flows_flow_type");

                    b.HasIndex("OrderCode")
                        .HasDatabaseName("idx_log_flows_order_code");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_log_flows_order_id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("idx_log_flows_partner_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("idx_log_flows_payment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_log_flows_status");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("idx_log_flows_transaction_id");

                    b.HasIndex("UserEmail")
                        .HasDatabaseName("idx_log_flows_user_email");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_log_flows_user_id");

                    b.ToTable("log_flows", (string)null);
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogAction", b =>
                {
                    b.HasOne("Skysim.Logger.Infrastructure.Entities.LogFlow", "Flow")
                        .WithMany("Actions")
                        .HasForeignKey("FlowId")
                        .HasPrincipalKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogActionDetail", b =>
                {
                    b.HasOne("Skysim.Logger.Infrastructure.Entities.LogAction", "Action")
                        .WithOne("Detail")
                        .HasForeignKey("Skysim.Logger.Infrastructure.Entities.LogActionDetail", "ActionId")
                        .HasPrincipalKey("LogAction", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogAction", b =>
                {
                    b.Navigation("Detail");
                });

            modelBuilder.Entity("Skysim.Logger.Infrastructure.Entities.LogFlow", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}